### ISSUE TITLE
Link to the table corpus

### ISSUE THREAD

**Issue by chabrowa** [iai-group/www2018-table#1]
Hi,
the following link in a readme file is not working:
http://gustav1.ux.uis.no/downloads/smart_table/WP_tables.zip
Could the data be accessed in any alternative way?

Thank you for any suggestions!

**Comment by imsure318** [comment]
Hi, I will double check the data, and let you know later on.

**Comment by imsure318** [comment]
Hi,

I turned to the others for the data accessibility, they all have no problem.
Could you double check it is okay right now, if no, I can try to share it with u using
other platforms. Cheers!

**Comment by chabrowa** [comment]
Hi, 

Thank you for looking into that! Unfortunately, it is still not working for me. I am getting the following message:  

> Forbidden
> You don't have permission to access /downloads/smart_table/WP_tables.zip on this server.
> 
> Apache/2.4.7 (Ubuntu) Server at gustav1.ux.uis.no Port 80

Maybe it is impossible to access from outside of the specific university network?

**Comment by imsure318** [comment]
Hi,

Plz find the tables over the link https://www.dropbox.com/s/zo2m6e3vf71d1oy/tables.zip?dl=0

-S

**Comment by chabrowa** [comment]
thanks a lot!
