### ISSUE TITLE
Prefixes max, sum, avg and sim

### ISSUE THREAD

**Issue by martijndeheus** [iai-group/www2018-table#2]
Hi,

I am working on replicating/reproducing this research and I was wondering what the prefixes represent in your ```features.csv```. 

The prefixes are:
- none
- e
- c
- re

And should (I think) correspond to:
- Bag-of-entities
- Bag-of-categories 
- Word embeddings
- Graph embeddings

I am having some trouble matching my results to them. Could you clarify how these link to eachother?

**Comment by imsure318** [comment]
Hi, Thanks for your interest. Here are the correspondences.

- none: word embeddings; 

- e: bag-of-entities;

- c: bag-of-categories

- re: Graph embeddings
